export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_SCORE_BOARD_START = "FETCH_SCORE_BOARD_START";
export const FETCH_SCORE_BOARD_SUCCESS = "FETCH_SCORE_BOARD_SUCCESS";
export const FETCH_SCORE_BOARD_FAIL = "FETCH_SCORE_BOARD_FAIL";

export const SEND_SCORE_START = "SEND_SCORE_START";
export const SEND_SCORE_SUCCESS = "SEND_SCORE_SUCCESS";
export const SEND_SCORE_FAIL = "SEND_SCORE_FAIL";
export const SEND_SCORE_FAIL_HOME = "SEND_SCORE_FAIL_HOME";

export const SET_BACK_TO_HOME = "SET_BACK_TO_HOME";
export const SET_LEVEL = "SET_LEVEL";
